[workspace]
resolver = "3"
members = [
  "crates/okibi-cli",
  "crates/okibi-core",
  "crates/okibi-qk",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/reearth/okibi"
rust-version = "1.85"
version = "0.0.0"

[workspace.dependencies]
okibi-core = { path = "crates/okibi-core", version = "0.0.0" }
okibi-qk = { path = "crates/okibi-qk", version = "0.0.0" }
